FROM golang:1.27-alpine AS build
ARG GOOSE_VERSION=v3.27.3
RUN GOBIN=/out go install github.com/pressly/goose/v3/cmd/goose@${GOOSE_VERSION}

FROM alpine:3.22
RUN apk add --no-cache ca-certificates
WORKDIR /workspace
COPY --from=build /out/goose /usr/local/bin/goose
COPY migrations ./migrations
COPY scripts/goose-fly-entrypoint.sh /usr/local/bin/goose-fly-entrypoint
RUN chmod +x /usr/local/bin/goose-fly-entrypoint
ENTRYPOINT ["/usr/local/bin/goose-fly-entrypoint"]
