FROM arigaio/atlas:1.3.3-alpine
WORKDIR /workspace

COPY atlas.hcl ./atlas.hcl
COPY schema ./schema
COPY scripts/atlas-fly-entrypoint.sh /usr/local/bin/atlas-fly-entrypoint

RUN chmod +x /usr/local/bin/atlas-fly-entrypoint

ENTRYPOINT ["/usr/local/bin/atlas-fly-entrypoint"]
