import * as stylex from "@stylexjs/stylex";

export const adminStyles = stylex.create({
  page: { minHeight: "100vh", backgroundColor: "#090909", color: "#f3f0e6", fontFamily: "Inter, ui-sans-serif, system-ui, sans-serif" },
  shell: { display: "grid", gridTemplateColumns: "190px minmax(0, 1fr)", minHeight: "100vh" },
  sidebar: { position: "sticky", top: 0, height: "100vh", borderRight: "1px solid #272727", padding: "24px 16px", backgroundColor: "#0d0d0d" },
  brand: { fontSize: 18, fontWeight: 800, letterSpacing: "-0.03em", marginBottom: 4 },
  adminLabel: { color: "#d8ff3e", fontSize: 10, fontWeight: 800, letterSpacing: ".16em", textTransform: "uppercase", marginBottom: 30 },
  nav: { display: "grid", gap: 6 },
  navLink: { display: "block", color: "#a7a7a0", textDecoration: "none", padding: "9px 10px", borderRadius: 6, fontSize: 13, ':hover': { color: "#f3f0e6", backgroundColor: "#171717" } },
  navActive: { color: "#f3f0e6", backgroundColor: "#1c1c1c" },
  backLink: { display: "block", marginTop: 30, color: "#696963", textDecoration: "none", fontSize: 11 },
  main: { minWidth: 0, padding: "26px 30px 60px" },
  topbar: { display: "flex", justifyContent: "space-between", gap: 20, alignItems: "flex-start", marginBottom: 24 },
  eyebrow: { color: "#8f8f88", fontSize: 10, letterSpacing: ".14em", textTransform: "uppercase", fontWeight: 800 },
  title: { fontSize: 28, lineHeight: 1.05, margin: "6px 0 5px", letterSpacing: "-0.04em" },
  copy: { margin: 0, color: "#85857e", fontSize: 13, maxWidth: 720, lineHeight: 1.5 },
  toolbar: { display: "flex", flexWrap: "wrap", gap: 8, alignItems: "center", marginBottom: 18 },
  select: { backgroundColor: "#111", color: "#e8e5dc", border: "1px solid #30302f", borderRadius: 5, padding: "7px 9px", fontSize: 12 },
  button: { backgroundColor: "#171717", color: "#e8e5dc", border: "1px solid #343432", borderRadius: 5, padding: "7px 10px", cursor: "pointer", fontSize: 12, ':hover': { borderColor: "#65655f" }, ':disabled': { opacity: .45, cursor: "default" } },
  buttonAccent: { backgroundColor: "#d8ff3e", color: "#090909", borderColor: "#d8ff3e", fontWeight: 800 },
  buttonDanger: { color: "#ff9e8f" },
  buttonQuiet: { color: "#aaa9a2" },
  status: { border: "1px solid #292929", backgroundColor: "#101010", padding: 14, fontSize: 12, color: "#aaa9a2", borderRadius: 6 },
  list: { display: "grid", gap: 9 },
  card: { border: "1px solid #282828", backgroundColor: "#0f0f0f", borderRadius: 7, padding: 16, display: "grid", gridTemplateColumns: "minmax(0, 1fr) auto", gap: 18 },
  score: { fontSize: 28, fontWeight: 900, letterSpacing: "-0.06em", color: "#d8ff3e", textAlign: "right" },
  scoreLabel: { color: "#65655f", fontSize: 9, textTransform: "uppercase", letterSpacing: ".12em" },
  meta: { display: "flex", flexWrap: "wrap", gap: 8, color: "#76766f", fontSize: 10, textTransform: "uppercase", letterSpacing: ".08em", marginBottom: 7 },
  headline: { fontSize: 16, lineHeight: 1.25, margin: 0, letterSpacing: "-0.015em" },
  description: { color: "#9c9b94", fontSize: 12, lineHeight: 1.5, margin: "8px 0 0", maxWidth: 900 },
  why: { color: "#c0bea9", fontSize: 11, marginTop: 10 },
  actions: { display: "flex", flexWrap: "wrap", gap: 7, marginTop: 13 },
  badge: { display: "inline-block", padding: "2px 6px", border: "1px solid #3a3a37", borderRadius: 999, fontSize: 9, color: "#a9a89f" },
  weird: { color: "#d8ff3e", borderColor: "#61721a" },
  panelGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))", gap: 10 },
  panel: { border: "1px solid #282828", borderRadius: 7, backgroundColor: "#0f0f0f", padding: 16 },
  metric: { fontSize: 24, fontWeight: 800, marginTop: 5 },
  noteArea: { width: "100%", minHeight: 92, resize: "vertical", boxSizing: "border-box", backgroundColor: "#0a0a0a", color: "#ece9df", border: "1px solid #30302f", borderRadius: 5, padding: 10, marginTop: 10, fontFamily: "inherit", fontSize: 13 },
  noteText: { whiteSpace: "pre-wrap", color: "#d5d2c9", lineHeight: 1.55, fontSize: 13 },
  sourceRow: { display: "grid", gridTemplateColumns: "minmax(180px, 1fr) repeat(4, minmax(80px, auto))", gap: 12, alignItems: "center", borderBottom: "1px solid #222", padding: "13px 0", fontSize: 12 },
  issueForm: { display: "grid", gap: 10, maxWidth: 900 },
  input: { backgroundColor: "#0d0d0d", color: "#eeeae0", border: "1px solid #30302f", borderRadius: 5, padding: "9px 10px", fontSize: 13 },
  issueSection: { marginTop: 22 },
  sectionTitle: { fontSize: 14, textTransform: "uppercase", letterSpacing: ".08em", color: "#bcbab0", margin: "0 0 9px" },
  itemLine: { display: "flex", justifyContent: "space-between", gap: 12, borderTop: "1px solid #222", padding: "10px 0", fontSize: 12 },
  empty: { border: "1px dashed #30302d", padding: 30, textAlign: "center", color: "#77776f", borderRadius: 7 },
  error: { color: "#ff9e8f", border: "1px solid #5a2d28", backgroundColor: "#1b0f0e", padding: 10, borderRadius: 5, fontSize: 12, marginBottom: 12 },
  success: { color: "#d8ff3e", fontSize: 11 },
});
