import * as stylex from "@stylexjs/stylex";

export const colors = stylex.defineVars({
  bg: "#090909",
  panel: "#111111",
  panel2: "#171717",
  line: "#292929",
  text: "#f4f1e8",
  muted: "#9c9a94",
  acid: "#d8ff3e",
  orange: "#ff7a3d",
  cyan: "#6ee7ff",
  violet: "#bb9cff",
});

export const styles = stylex.create({
  page: {
    minHeight: "100vh",
    backgroundColor: colors.bg,
    color: colors.text,
    fontFamily: 'Inter, ui-sans-serif, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
  },
  shell: {
    width: "100%",
    maxWidth: "1240px",
    marginInline: "auto",
    paddingInline: { default: "28px", "@media (max-width: 720px)": "16px" },
  },
  header: {
    minHeight: "74px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "22px",
    borderBottom: `1px solid ${colors.line}`,
  },
  brand: {
    textDecoration: "none",
    display: "flex",
    alignItems: "center",
    gap: "10px",
    fontSize: "20px",
    fontWeight: 850,
    letterSpacing: "-0.04em",
  },
  brandMark: {
    width: "28px",
    height: "28px",
    display: "grid",
    placeItems: "center",
    borderRadius: "8px",
    backgroundColor: colors.acid,
    color: colors.bg,
    fontSize: "15px",
    fontWeight: 950,
    transform: "rotate(-4deg)",
  },
  nav: {
    display: { default: "flex", "@media (max-width: 720px)": "none" },
    alignItems: "center",
    gap: "8px",
  },
  navLink: {
    textDecoration: "none",
    color: colors.muted,
    padding: "9px 12px",
    borderRadius: "999px",
    fontSize: "14px",
    fontWeight: 700,
    transition: "160ms ease",
    ":hover": { color: colors.text, backgroundColor: colors.panel2 },
  },
  headerAction: {
    textDecoration: "none",
    border: `1px solid ${colors.line}`,
    borderRadius: "999px",
    padding: "9px 12px",
    color: colors.text,
    fontSize: "13px",
    fontWeight: 800,
  },
  main: { paddingBlock: "34px 64px" },
  eyebrow: {
    color: colors.acid,
    fontSize: "12px",
    fontWeight: 900,
    letterSpacing: "0.14em",
    textTransform: "uppercase",
  },
  hero: {
    paddingBlock: "34px 30px",
    display: "grid",
    gridTemplateColumns: { default: "minmax(0, 1.35fr) minmax(280px, .65fr)", "@media (max-width: 820px)": "1fr" },
    gap: "28px",
    alignItems: "end",
  },
  heroTitle: {
    margin: "8px 0 10px",
    maxWidth: "820px",
    fontSize: { default: "clamp(44px, 7vw, 86px)", "@media (max-width: 720px)": "46px" },
    lineHeight: 0.94,
    letterSpacing: "-0.065em",
    fontWeight: 900,
  },
  heroAccent: { color: colors.acid },
  heroCopy: {
    color: colors.muted,
    fontSize: "17px",
    lineHeight: 1.6,
    maxWidth: "540px",
    margin: 0,
  },
  statusCard: {
    border: `1px solid ${colors.line}`,
    borderRadius: "20px",
    padding: "20px",
    backgroundColor: colors.panel,
  },
  statusLabel: { color: colors.muted, fontSize: "12px", fontWeight: 800, textTransform: "uppercase", letterSpacing: "0.11em" },
  statusValue: { fontSize: "34px", fontWeight: 900, marginBlock: "8px 2px", letterSpacing: "-0.04em" },
  statusSub: { color: colors.muted, fontSize: "13px", lineHeight: 1.5 },
  tabs: {
    display: "flex",
    gap: "8px",
    overflowX: "auto",
    paddingBottom: "18px",
    borderBottom: `1px solid ${colors.line}`,
  },
  tab: {
    textDecoration: "none",
    whiteSpace: "nowrap",
    color: colors.muted,
    border: `1px solid ${colors.line}`,
    borderRadius: "999px",
    padding: "9px 14px",
    fontSize: "13px",
    fontWeight: 800,
    ":hover": { color: colors.bg, backgroundColor: colors.acid, borderColor: colors.acid },
  },
  section: { paddingTop: "28px" },
  sectionHeader: { display: "flex", justifyContent: "space-between", alignItems: "end", gap: "20px", marginBottom: "16px" },
  sectionTitle: { margin: 0, fontSize: "23px", fontWeight: 900, letterSpacing: "-0.03em" },
  sectionCopy: { margin: 0, color: colors.muted, fontSize: "13px" },
  trendList: { display: "grid", gap: "9px" },
  trendRow: {
    display: "grid",
    gridTemplateColumns: { default: "48px minmax(0, 1.2fr) 110px 95px minmax(220px, 1fr) 56px", "@media (max-width: 900px)": "40px minmax(0,1fr) 84px 56px" },
    gap: "14px",
    alignItems: "center",
    minHeight: "82px",
    padding: "13px 16px",
    border: `1px solid ${colors.line}`,
    borderRadius: "16px",
    backgroundColor: colors.panel,
    textDecoration: "none",
    transition: "160ms ease",
    ":hover": { borderColor: "#4a4a4a", transform: "translateY(-1px)", backgroundColor: colors.panel2 },
  },
  rank: { color: colors.muted, fontSize: "16px", fontWeight: 800 },
  trendName: { fontSize: "17px", fontWeight: 900, letterSpacing: "-0.02em" },
  trendMeta: { color: colors.muted, fontSize: "11px", fontWeight: 800, marginTop: "4px", letterSpacing: "0.06em" },
  score: { fontSize: "22px", fontWeight: 950, textAlign: "right", letterSpacing: "-0.04em" },
  change: { color: colors.acid, fontSize: "13px", fontWeight: 900, textAlign: "right" },
  reason: { color: colors.muted, fontSize: "13px", lineHeight: 1.45, display: { default: "block", "@media (max-width: 900px)": "none" } },
  arrow: { textAlign: "right", fontSize: "18px" },
  grid3: { display: "grid", gridTemplateColumns: { default: "repeat(3, 1fr)", "@media (max-width: 820px)": "1fr" }, gap: "14px" },
  card: { border: `1px solid ${colors.line}`, borderRadius: "18px", backgroundColor: colors.panel, padding: "20px" },
  cardKicker: { color: colors.acid, fontSize: "11px", fontWeight: 900, letterSpacing: "0.12em", textTransform: "uppercase" },
  cardTitle: { margin: "10px 0 7px", fontSize: "21px", fontWeight: 900, letterSpacing: "-0.03em" },
  cardCopy: { margin: 0, color: colors.muted, lineHeight: 1.55, fontSize: "14px" },
  scoreBig: { fontSize: "64px", fontWeight: 950, lineHeight: 1, letterSpacing: "-0.07em" },
  detailHero: { display: "grid", gridTemplateColumns: { default: "minmax(0, 1.4fr) minmax(260px, .6fr)", "@media (max-width: 820px)": "1fr" }, gap: "20px", paddingBlock: "26px" },
  detailTitle: { margin: "8px 0", fontSize: "clamp(48px, 7vw, 82px)", lineHeight: 0.95, letterSpacing: "-0.06em", fontWeight: 950 },
  chips: { display: "flex", gap: "8px", flexWrap: "wrap", marginTop: "18px" },
  chip: { border: `1px solid ${colors.line}`, borderRadius: "999px", padding: "7px 10px", color: colors.muted, fontSize: "12px", fontWeight: 800 },
  actionGrid: { display: "grid", gridTemplateColumns: { default: "repeat(4, 1fr)", "@media (max-width: 720px)": "repeat(2, 1fr)" }, gap: "10px", marginBottom: "18px" },
  actionCard: { textDecoration: "none", padding: "15px", borderRadius: "15px", border: `1px solid ${colors.line}`, backgroundColor: colors.panel, fontWeight: 900, ":hover": { borderColor: colors.acid } },
  actionLabel: { display: "block", color: colors.muted, fontSize: "11px", marginTop: "5px", fontWeight: 700 },
  twoCol: { display: "grid", gridTemplateColumns: { default: "minmax(0, 1.25fr) minmax(280px, .75fr)", "@media (max-width: 820px)": "1fr" }, gap: "16px" },
  whyBox: { border: `1px solid ${colors.line}`, borderRadius: "20px", padding: "24px", backgroundColor: colors.panel },
  whyTitle: { margin: "6px 0 12px", fontSize: "30px", fontWeight: 950, letterSpacing: "-0.045em" },
  whyCopy: { color: "#d3d0c8", lineHeight: 1.7, fontSize: "16px", margin: 0 },
  timeline: { display: "grid", gap: "0" },
  timelineItem: { display: "grid", gridTemplateColumns: "64px 1fr", gap: "16px", paddingBlock: "15px", borderBottom: `1px solid ${colors.line}` },
  timelineTime: { color: colors.acid, fontFamily: "ui-monospace, SFMono-Regular, Menlo, monospace", fontSize: "12px", fontWeight: 900 },
  timelineTitle: { fontWeight: 900, marginBottom: "5px" },
  timelineCopy: { color: colors.muted, fontSize: "13px", lineHeight: 1.5 },
  ask: { border: `1px solid ${colors.line}`, borderRadius: "20px", padding: "18px", backgroundColor: colors.panel2 },
  askInput: { width: "100%", border: 0, outline: 0, backgroundColor: "transparent", color: colors.text, fontSize: "17px", padding: "6px 0 13px" },
  askSuggestions: { display: "flex", gap: "7px", flexWrap: "wrap" },
  smallButton: { border: `1px solid ${colors.line}`, backgroundColor: colors.panel, color: colors.muted, borderRadius: "999px", padding: "7px 9px", fontSize: "11px", fontWeight: 800 },
  emptyState: { padding: "60px 20px", textAlign: "center", border: `1px dashed ${colors.line}`, borderRadius: "20px" },
  fomoRow: { display: "grid", gridTemplateColumns: { default: "130px minmax(0,1fr) 110px", "@media (max-width: 720px)": "1fr" }, gap: "14px", padding: "20px 0", borderBottom: `1px solid ${colors.line}` },
  fomoTime: { color: colors.acid, fontSize: "12px", fontWeight: 900, textTransform: "uppercase" },
  followButton: { border: `1px solid ${colors.line}`, backgroundColor: colors.acid, color: colors.bg, borderRadius: "999px", padding: "9px 13px", fontWeight: 900, fontSize: "12px" },
  footer: { display: "flex", justifyContent: "space-between", gap: "20px", paddingBlock: "24px 38px", borderTop: `1px solid ${colors.line}`, color: colors.muted, fontSize: "12px" },
});
