import * as stylex from "@stylexjs/stylex";
import { colors } from "./styles.stylex";

export const intelligenceStyles = stylex.create({
  evidenceGrid: {
    display: "grid",
    gridTemplateColumns: { default: "repeat(2, minmax(0, 1fr))", "@media (max-width: 760px)": "1fr" },
    gap: "10px",
    marginTop: "18px",
  },
  evidence: {
    display: "block",
    padding: "14px",
    border: `1px solid ${colors.line}`,
    borderRadius: "14px",
    backgroundColor: colors.panel2,
    color: colors.text,
    textDecoration: "none",
  },
  evidenceSource: {
    color: colors.acid,
    fontSize: "10px",
    fontWeight: 900,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
  },
  evidenceTitle: {
    marginTop: "6px",
    fontSize: "13px",
    lineHeight: 1.45,
    fontWeight: 750,
  },
  path: {
    display: "flex",
    gap: "8px",
    alignItems: "stretch",
    overflowX: "auto",
    paddingBottom: "8px",
  },
  hop: {
    minWidth: "170px",
    padding: "14px",
    border: `1px solid ${colors.line}`,
    borderRadius: "14px",
    backgroundColor: colors.panel,
  },
  hopName: {
    fontWeight: 900,
    fontSize: "14px",
  },
  hopMeta: {
    color: colors.muted,
    fontSize: "11px",
    lineHeight: 1.5,
    marginTop: "8px",
  },
  arrow: {
    alignSelf: "center",
    color: colors.acid,
    fontWeight: 950,
    fontSize: "18px",
  },
  perspective: {
    display: "grid",
    gridTemplateColumns: { default: "repeat(7, minmax(0, 1fr))", "@media (max-width: 900px)": "repeat(4, minmax(0, 1fr))", "@media (max-width: 560px)": "repeat(2, minmax(0, 1fr))" },
    gap: "8px",
    marginTop: "16px",
  },
  perspectiveCell: {
    padding: "12px",
    border: `1px solid ${colors.line}`,
    borderRadius: "12px",
    backgroundColor: colors.panel2,
  },
  perspectiveValue: {
    fontSize: "22px",
    fontWeight: 950,
  },
  perspectiveLabel: {
    marginTop: "4px",
    color: colors.muted,
    fontSize: "9px",
    fontWeight: 900,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
  },
  askForm: {
    display: "flex",
    gap: "8px",
    marginTop: "12px",
  },
  askButton: {
    border: 0,
    borderRadius: "12px",
    backgroundColor: colors.acid,
    color: colors.bg,
    padding: "0 16px",
    fontWeight: 950,
    cursor: "pointer",
  },
  answer: {
    marginTop: "16px",
    padding: "16px",
    borderLeft: `3px solid ${colors.acid}`,
    backgroundColor: colors.panel2,
    borderRadius: "0 12px 12px 0",
    lineHeight: 1.6,
  },
  answerMeta: {
    marginTop: "8px",
    color: colors.muted,
    fontSize: "10px",
    fontWeight: 800,
    textTransform: "uppercase",
    letterSpacing: "0.06em",
  },
  voices: {
    display: "flex",
    flexWrap: "wrap",
    gap: "8px",
    marginTop: "14px",
  },
  voice: {
    padding: "8px 11px",
    border: `1px solid ${colors.line}`,
    borderRadius: "999px",
    backgroundColor: colors.panel2,
    fontSize: "12px",
    fontWeight: 800,
  },
});
